### ISSUE TITLE
Support custom vue content by plugins to be sent to the client

### ISSUE THREAD

**Issue by vainamov** [festivaledu/neo#50]

**Comment by SniperGER** [comment]
Let's start by adding a basic plugin folder structure:

```
.
└── plugins
    └── ml.festival.example
        └── resources
        │   └── test.txt
        └── plugin.dll
```

_(Depicted file structure may not represent actual file structure)_

`plugin.dll` basically loads `test.txt` as a byte array using `File.readAllBytes(String path)`, hands it over to the WebSocket, which then sends it to the client. Since the client is based on node, it *should* be possible to convert the byte array back to text.

Next would be handling `.vue`-Files, which _could_ work with either `new Vue()` or somehow using `render(h)`

**Comment by SniperGER** [comment]
Client is unable to correctly initialize Vue-based plugin resources.

Current idea is to hardcode plugins (private messages, surveys)
