### ISSUE TITLE
Communicate asynchronously (COM-2)

### ISSUE THREAD

**Issue by wearefestival** [festivaledu/neo#8]
Whenever possible and suitable, an asynchronous pattern should be used.

**Comment by vainamov** [comment]
This has been done in festivaledu/neo-core@b1c2719 for the core/server side.

**Comment by vainamov** [comment]
Due to WebSocketSharps event based pattern, second-level asynchronous pattern is not only unneccessary but also breaks the order of the packages. This was proposed because of existing experience based with Streams which require asnychronous patterns.

The broken changes made to the project in festivaledu/neo-core@b1c2719 have been fixed in festivaledu/neo-core@d0d7bde.
